services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://192.168.0.213}
    image: vestis_frontend:local
    container_name: vestis_frontend
    networks:
      - wardrobe-shared
    restart: on-failure

networks:
  wardrobe-shared:
    external: true
    name: ${WARDROBE_DOCKER_NETWORK:-wardrobe-service_wardrobe-network}
